import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header/page";
import Footer from "@/components/ui/Footer/page";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Sidebar from "@/components/ui/Sidebar/page";
import Link from 'next/link'
import { IoMdArrowBack } from "react-icons/io";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className }>
      <StoreProvider>
      <Header></Header>
      <div className="">
     <div className="flex flex-row px-10 gap-5 min-h-[50vh]">
     <Sidebar></Sidebar>
     <div className="w-[100%]">
      <Link href={`/`}>
      <p className="cursor-pointer"><IoMdArrowBack/></p>
      </Link>
     <AntdRegistry>{children}</AntdRegistry>
     </div>
     </div>
       <Footer></Footer>
      </div>
      </StoreProvider>
      
      </body>
    </html>
  );
}
